### PR TITLE
Add Detect tag without new commit workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
It should find these.
```
d03c4d7f50770a0f362a695668c57b58a78c63d0 refs/tags/0.2.90
d03c4d7f50770a0f362a695668c57b58a78c63d0 refs/tags/0.2.91

592e64622127c51b7ab0cc3213b85dfcdc8b9b0b refs/tags/0.3.14
592e64622127c51b7ab0cc3213b85dfcdc8b9b0b refs/tags/0.3.15
592e64622127c51b7ab0cc3213b85dfcdc8b9b0b refs/tags/0.3.16

eb43ed0326dc8a2934ed1b8601fc4279d36f7a91 refs/tags/0.3.25
eb43ed0326dc8a2934ed1b8601fc4279d36f7a91 refs/tags/0.3.26

54fc98543a6d304e28fd903f347a63384c5b4f93 refs/tags/0.3.27
54fc98543a6d304e28fd903f347a63384c5b4f93 refs/tags/0.3.28

8e7230b36dd568095d964dc0bd64e84e68cc5dcb refs/tags/0.3.42
8e7230b36dd568095d964dc0bd64e84e68cc5dcb refs/tags/0.3.43
```
Then I should come up with an exclusion list.

### CODE REVIEW

**Comment by szepeviktor** [comment]
```bash
test "$(git show-ref --tags | cut -d ' ' -f 1 | sort | uniq -d)" == \
"54fc98543a6d304e28fd903f347a63384c5b4f93
592e64622127c51b7ab0cc3213b85dfcdc8b9b0b
8e7230b36dd568095d964dc0bd64e84e68cc5dcb
d03c4d7f50770a0f362a695668c57b58a78c63d0
eb43ed0326dc8a2934ed1b8601fc4279d36f7a91"
```

**Comment by BenMorel** [comment]
Hi, thanks for your PR! Does that actually prevent the tag from being created? I fail to understand if the CI runs after or before the tag is pushed.

**Comment by szepeviktor** [comment]
You have to hire a magician to know about a tag **before** it is created :)

**Comment by szepeviktor** [comment]
The only "before" place is your local machine.
```
$ git show-ref --tags --hash=7 | sort | uniq -d
```
Maybe a git alias!

**Comment by szepeviktor** [comment]
Hello @BenMorel!

https://github.com/nicebooks-com/isbn/compare/0.4.8...0.4.9

We have this problem again.
Please consider merging this PR.

**Comment by szepeviktor** [comment]
I've just realized I do something very similar over at @php-stubs with million download packages.

1. git commit and git tag locally
2. git push
3. see CI output on GitHub
4. if it is okay: git push --tags

**Comment by BenMorel** [comment]
Thanks for bringing this to my attention, @szepeviktor. Honestly this is becoming a burden and I'll probably make a scheduled job at some point to create new releases automatically, provided they pass the CI.

In the meantime, let's merge this!

What happens when the job fails though, where do I get notified?

**Comment by szepeviktor** [comment]
It runs when you push a tag or create it on GitHub's release UI.
Just check Actions right after that. Is should also send you an email.

But first we have to exclude already multi-tagged commits!

**Comment by BenMorel** [comment]
> But first we have to exclude already multi-tagged commits!

Sure. I don't think it's a good idea to delete  / change tags, so do you want to add offending commit hashes in the script?

**Pull request merged**
