### PR TITLE
Fetch all in duplicate-tags.yml

### PR DESCRIPTION
**Pull request by szepeviktor**
After this it works!

image

### CODE REVIEW

**Comment by szepeviktor** [comment]
I'm just debugging the Exclusion System 🙃 
🖱️  https://github.com/szepeviktor/isbn/actions/runs/6998600501/job/19036826875

**Comment by szepeviktor** [comment]
@BenMorel Now it is complete and working.

**Comment by BenMorel** [comment]
Thank you, @szepeviktor!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
