### PR TITLE
Update gitattributes

### PR DESCRIPTION
**Pull request by szepeviktor**
- Bye-bye Travis CI! 👋🏻
- Have a seat GHA and `psalm.xml`

Here is how to test
```bash
git archive HEAD | tar --list --exclude='src' --exclude='src/*'
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
My default value for the export-checking CI workflow [includes README](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/integrity.yml#L35).

**Comment by BenMorel** [comment]
I guess it makes sense to import the README indeed. Can you please update accordingly?

> git archive HEAD | tar --list --exclude='src' --exclude='src/*'

:heart: this command, thank you!

**Comment by szepeviktor** [comment]
> Can you please update accordingly?

Done 🍏

**Comment by BenMorel** [comment]
Thank you! :racehorse:

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
